mkdir -p fish
mkdir -p fish/conf.d
cp ~/.config/nvim/init.vim init.vim
cp ~/.config/nvim/plugin_conf.vim plugin_conf.vim
cp ~/.config/nvim/theming.vim theming.vim
cp ~/.config/nvim/general.vim general.vim
cp ~/.config/nvim/keys.vim keys.vim
cp ~/.alacritty.yml .alacritty.yml
cp ~/.skhdrc .skhdrc
cp ~/.yabairc .yabairc
cp ~/.tmux.conf .tmux.conf
cp ~/.config/fish/conf.d/omf.fish fish/conf.d/omf.fish
cp ~/.config/fish/config.fish fish/config.fish
cp ~/.config/fish/fish_variables fish/fish_variables
